### ISSUE TITLE
Is the MOSEI dataset still available?

### ISSUE THREAD

**Issue by W-ZN** [CMU-MultiComp-Lab/CMU-MultimodalSDK#16]
I am unable to download MOSEI locally through the SDK. It seems that there are no files available at http://immortal.multicomp.cs.cmu.edu. Can you provide a solution to address this issue?

**Comment by MatFil99** [comment]
Not just MOSEI, I can't download any of the datasets. Could you fix the problem

**Comment by lpmorency** [comment]
The server Immortal should be back online. Please try again. Best.



*From:* F.Mazur ***@***.***>
*Sent:* Saturday, March 23, 2024 8:45
*To:* CMU-MultiComp-Lab/CMU-MultimodalSDK <
***@***.***>
*Cc:* Subscribed ***@***.***>
*Subject:* Re: [CMU-MultiComp-Lab/CMU-MultimodalSDK] Is the MOSEI dataset
still available? (Issue #16)



Not just MOSEI, I can't download any of the datasets

—
Reply to this email directly, view it on GitHub
<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCMU-MultiComp-Lab%2FCMU-MultimodalSDK%2Fissues%2F16%23issuecomment-2016483688&data=05%7C02%7C%7C8949cd2a1cce4cc8ed1f08dc4b37167b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638467947176528404%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=YQXLk0zTZYsixM2ojDIv7wTElpwmAOuUw5Z%2BCLwfi48%3D&reserved=0>,
or unsubscribe
<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADSLKA6ZFDDDSZUYEM7BKRLYZV2NVAVCNFSM6AAAAABFCXDZI6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJWGQ4DGNRYHA&data=05%7C02%7C%7C8949cd2a1cce4cc8ed1f08dc4b37167b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638467947176539437%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=6Cn7KlLkhbWGMdJMtwTLMlb8mOVn8Bf5thyFu%2FPE5bs%3D&reserved=0>
.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by W-ZN** [comment]
> The server Immortal should be back online. Please try again. Best. *From:* F.Mazur ***@***.***> *Sent:* Saturday, March 23, 2024 8:45 *To:* CMU-MultiComp-Lab/CMU-MultimodalSDK < ***@***.***> *Cc:* Subscribed ***@***.***> *Subject:* Re: [CMU-MultiComp-Lab/CMU-MultimodalSDK] Is the MOSEI dataset still available? (Issue #16) Not just MOSEI, I can't download any of the datasets — Reply to this email directly, view it on GitHub <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCMU-MultiComp-Lab%2FCMU-MultimodalSDK%2Fissues%2F16%23issuecomment-2016483688&data=05%7C02%7C%7C8949cd2a1cce4cc8ed1f08dc4b37167b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638467947176528404%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=YQXLk0zTZYsixM2ojDIv7wTElpwmAOuUw5Z%2BCLwfi48%3D&reserved=0>, or unsubscribe <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADSLKA6ZFDDDSZUYEM7BKRLYZV2NVAVCNFSM6AAAAABFCXDZI6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJWGQ4DGNRYHA&data=05%7C02%7C%7C8949cd2a1cce4cc8ed1f08dc4b37167b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638467947176539437%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=6Cn7KlLkhbWGMdJMtwTLMlb8mOVn8Bf5thyFu%2FPE5bs%3D&reserved=0> . You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Thank you for your response! I am now able to use it normally!
